version: '3.0'

services:
  app:
    container_name: app_service
    build:
      context: .
      dockerfile: _dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    restart: "always"
  
  database:
    image: mongo:latest
    ports:
    - "27017:27017"